### PR TITLE
a-c from Wikipedia

### PR DESCRIPTION
**Pull request by todrobbins**
source: https://en.wikipedia.org/wiki/List_of_dinosaur_genera

### CODE REVIEW

**Comment by jden** [comment]
thanks! are you doing these manually?

**Comment by jden** [comment]
published [dinosaurs@1.1.0](https://npm.im/dinosaurs)

**Comment by todrobbins** [comment]
Yeah... at least only multiline editing in Sublime. My cli skills are rudimentary. What would you recommend for parsing the wikitext?

**Comment by jden** [comment]
Here's a quick javascript snippet I put together to try to guess and scrape things from that page. Wikipedia is kind of notorious for being hard to scrape, but at a glance the list looks right:

(run in the Chrome DevTools console):
`copy([].slice.call(document.querySelectorAll('li > i:first-child > a')).map(function (el) { return el.textContent }).join('\n'))`

https://gist.github.com/jden/1be41da4e6d6f92d7ca6

**Comment by jden** [comment]
I'd be super grateful for a pull request incorporating that list with the dinosaurs already in this repo!

**Pull request merged**
